// src/react/BookmarksPanel.tsx
import { useStore } from '@nanostores/react';
import { locale, settings } from '../core/settings.ts';
import {
  buttonBookmark,
  buttonBookmarksClose,
  buttonEraseBookmarks,
} from '../ui/events/bookmarks.ts';
import { isEmpty } from '../utils/checks.ts';
import { IconBookmark, IconBookmarkOff, IconExternalLink, IconTrash, IconX } from './Icons.ts';

function BookmarksPanel() {
  const l = useStore(locale);
  const s = useStore(settings);

  return (
    <div id="BookmarksPanel" className="panel">
      <button
        id="CloseBookmarks"
        className="closeButton"
        title={l.CLOSE}
        onClick={buttonBookmarksClose}
        type="button"
      >
        <IconX />
      </button>
      <button
        className="Bookmark simpleButton"
        title={l.BOOKMARK}
        type="button"
        onClick={buttonBookmark}
      >
        <IconBookmark />
        <IconBookmarkOff />
      </button>
      <h2>{l.BOOKMARKS}</h2>
      <div id="BookmarksList">
        {isEmpty(s.bookmarks)
          ? l.LIST_EMPTY
          : s.bookmarks.map((mark, index) => (
              <div id={`Bookmark${index + 1}`} className="BookmarkItem" key={mark.url}>
                <span className="bookmarkColumnLarge">
                  <span className="bookmarkName">{mark.name}</span>
                  <br />
                  <a className="bookmarkURl" href={mark.url} target="_blank" rel="noreferrer">
                    {mark.url}
                  </a>
                </span>
                <span className="bookmarkColumnSmall">
                  <span className="bookmarkDate">
                    {new Date(mark.date).toISOString().slice(0, 10)}
                  </span>
                  <br />
                  <span className="bookmarkPage">Page: {mark.page}</span>
                </span>
                <span className="bookmarkFunctions">
                  <a href={mark.url} target="_blank" rel="noreferrer">
                    <button className="ControlButton open" title="Open Bookmark" type="button">
                      <IconExternalLink />
                    </button>
                  </a>
                  <button
                    className="ControlButton erase"
                    title="Delete Bookmark"
                    type="button"
                    value={mark.url}
                    onClick={buttonEraseBookmarks}
                  >
                    <IconTrash />
                  </button>
                </span>
              </div>
            ))}
      </div>
    </div>
  );
}

export default BookmarksPanel;

// src/svelte/BookmarksPanel.svelte
<script lang="ts">
  import { locale, settings } from '../core/settings';
  import { buttonBookmarksClose, buttonEraseBookmarks } from '../ui/events/bookmarks.ts';
  import { isEmpty } from '../utils/checks';
  import { IconBookmark, IconBookmarkOff, IconExternalLink, IconTrash, IconX } from '../ui/icons';
</script>

<div class="panel" id="BookmarksPanel">
  <button
    class="closeButton"
    id="CloseBookmarks"
    onclick={buttonBookmarksClose}
    title={$locale.CLOSE}
  >
    {@html IconX}
  </button>
  <button class="Bookmark simpleButton" title="${$locale.BOOKMARK}">
    {@html IconBookmark}
    {@html IconBookmarkOff}
  </button>
  <h2>{$locale.BOOKMARKS}</h2>
  <div id="BookmarksList">
    {#if isEmpty($settings.bookmarks)}
      {$locale.LIST_EMPTY}
    {:else}
      {#each $settings.bookmarks as mark, index (index)}
        <div id="Bookmark{index + 1}" class="BookmarkItem">
          <span class="bookmarkColumnLarge">
            <span class="bookmarkName">{mark.name}</span>
            <br />
            <a class="bookmarkURl" href={mark.url} target="_blank">{mark.url}</a>
          </span>
          <span class="bookmarkColumnSmall">
            <span class="bookmarkDate">
              {new Date(mark.date).toISOString().slice(0, 10)}
            </span>
            <br />
            <span class="bookmarkPage">Page: {mark.page}</span>
          </span>
          <span class="bookmarkFunctions">
            <a class="" href={mark.url} target="_blank">
              <button class="ControlButton open" title="Open Bookmark" type="button">
                {@html IconExternalLink}
              </button>
            </a>
            <button
              class="ControlButton erase"
              title="Delete Bookmark"
              type="button"
              value={mark.url}
              onclick={buttonEraseBookmarks}
            >
              {@html IconTrash}
            </button>
          </span>
        </div>
      {/each}
    {/if}
  </div>
</div>

<style>
</style>
