// src/react/KeybindingsPanel.tsx
import { useStore } from '@nanostores/react';
import { useState } from 'react';
import { locale, settings } from '../core/settings.ts';
import { isKey } from '../types';
import { buttonKeybindingsClose, editKeybindings, saveKeybindings } from '../ui/events/panels.ts';
import { IconDeviceFloppy, IconPencil, IconX } from './Icons.ts';

function KeybindingsPanel() {
  const l = useStore(locale);
  const s = useStore(settings);
  const [editor, setEditor] = useState(false);

  const handleEdit = () => {
    editKeybindings();
    setEditor(true);
  };

  const handleSave = () => {
    saveKeybindings();
    setEditor(false);
  };

  return (
    <div
      id="KeybindingsPanel"
      className="panel"
    >
      <h2>{l.KEYBINDINGS}</h2>
      <button
        id="CloseKeybindings"
        className="closeButton"
        title={l.CLOSE}
        onClick={buttonKeybindingsClose}
        type="button"
      >
        <IconX />
      </button>
      <div className="controls">
        <button
          id="EditKeybindings"
          className="ControlButton"
          type="button"
          title={l.EDIT_KEYBINDS}
          onClick={handleEdit}
        >
          <IconPencil />
          {l.BUTTON_EDIT}
        </button>
        <button
          id="SaveKeybindings"
          className="ControlButton hidden"
          type="button"
          title={l.SAVE_KEYBINDS}
          onClick={handleSave}
        >
          <IconDeviceFloppy />
          {l.BUTTON_SAVE}
        </button>
      </div>
      <div id="KeybindingsList">
        {!editor ? (
          Object.keys(s.keybinds).map(kb => (
            <span key={kb}>
              <span>{isKey(l, kb) ? l[kb] : ''}:</span>
              <span>
                {s.keybinds[kb]?.map((key: string) => (
                  <kbd
                    className="dark"
                    key={key}
                  >
                    {key}
                  </kbd>
                ))}
              </span>
            </span>
          ))
        ) : (
          <>
            {Object.keys(s.keybinds).map(kb => (
              <label
                htmlFor={kb}
                key={kb}
              >
                {isKey(l, kb) ? l[kb] : ''}:
                <input
                  type="text"
                  className="KeybindInput"
                  id={kb}
                  name={kb}
                  defaultValue={s.keybinds[kb]?.join(' , ') ?? ''}
                />
              </label>
            ))}
            <div id="HotKeysRules">{l.KEYBIND_RULES}</div>
          </>
        )}
      </div>
    </div>
  );
}

export default KeybindingsPanel;

// src/svelte/KeybindingsPanel.svelte
<script lang="ts">
    import { _ as getLocaleString } from 'svelte-i18n';
    import settings from '../core/settings';
    import IconX from './icons/x.svelte';
    import IconPencil from './icons/pencil.svelte';
    import IconDeviceFloppy from './icons/device-floppy.svelte';

    let editor = $state(false);

    function toggle() {
        editor = !editor;
    }
</script>

<div id="KeybindingsPanel" class="panel">
    <h2>{$getLocaleString('KEYBINDINGS')}</h2>
    <button id="CloseKeybindings" class="closeButton" title={$getLocaleString('CLOSE')}>
        <IconX />
    </button>
    <div class="controls">
        <button
            id="EditKeybindings"
            class="ControlButton"
            type="button"
            title={$getLocaleString('EDIT_KEYBINDS')}
            onclick={toggle}
        >
            <IconPencil />
            {$getLocaleString('BUTTON_EDIT')}
        </button>
        <button
            id="SaveKeybindings"
            class="ControlButton hidden"
            type="button"
            title={$getLocaleString('SAVE_KEYBINDS')}
            onclick={toggle}
        >
            <IconDeviceFloppy />
            {$getLocaleString('BUTTON_SAVE')}
        </button>
    </div>
    <div id="KeybindingsList">
        {#if !editor}
            {#each Object.keys($settings.keybinds) as kb}
                <span>{$getLocaleString(kb)}:</span>
                <span>
                    {#if $settings.keybinds[kb]}
                        {#each $settings.keybinds[kb] || [] as key}
                            <kbd class="dark">{key}</kbd>
                        {/each}
                    {/if}
                </span>
            {/each}
        {:else}
            {#each Object.keys($settings.keybinds) as kb}
                <label for={kb}>{$getLocaleString(kb)}:</label>
                <input
                    type="text"
                    class="KeybindInput"
                    id={kb}
                    name={kb}
                    value={$settings.keybinds[kb]?.join(' , ') ?? ''}
                />
            {/each}
            <div id="HotKeysRules">{$getLocaleString('KEYBIND_RULES')}</div>
        {/if}
    </div>
</div>

<style>
</style>
