// src/react/MangaPage.tsx
import { useStore } from '@nanostores/react';
import { locale } from '../core/settings.ts';
import { buttonBookmark } from '../ui/events/bookmarks.ts';
import { buttonHidePage, buttonReloadPage } from '../ui/events/individual.ts';
import {
  buttonRestoreZoom,
  buttonZoomHeight,
  buttonZoomIn,
  buttonZoomOut,
  buttonZoomWidth,
} from '../ui/events/size.ts';
import {
  IconArrowAutofitHeight,
  IconArrowAutofitWidth,
  IconBookmark,
  IconBookmarkOff,
  IconEye,
  IconEyeOff,
  IconRefresh,
  IconZoomCancel,
  IconZoomIn,
  IconZoomOut,
} from './Icons.ts';

type Props = {
  index: number;
  src?: string;
};

function MangaPage({ index, src = '' }: Props) {
  const l = useStore(locale);

  return (
    <div
      id={`Page${index}`}
      className="MangaPage"
    >
      <div className="PageFunctions">
        <button
          className="Bookmark ControlButton"
          title={l.BOOKMARK}
          onClick={buttonBookmark}
          type="button"
        >
          <IconBookmark />
          <IconBookmarkOff />
        </button>
        <button
          className="ZoomIn ControlButton"
          title={l.ZOOM_IN}
          onClick={buttonZoomIn}
          type="button"
        >
          <IconZoomIn />
        </button>
        <button
          className="ZoomRestore ControlButton"
          title={l.ZOOM_RESET}
          onClick={buttonRestoreZoom}
          type="button"
        >
          <IconZoomCancel />
        </button>
        <button
          className="ZoomOut ControlButton"
          title={l.ZOOM_OUT}
          onClick={buttonZoomOut}
          type="button"
        >
          <IconZoomOut />
        </button>
        <button
          className="ZoomWidth ControlButton"
          title={l.ZOOM_WIDTH}
          onClick={buttonZoomWidth}
          type="button"
        >
          <IconArrowAutofitWidth />
        </button>
        <button
          className="ZoomHeight ControlButton"
          title={l.ZOOM_HEIGHT}
          onClick={buttonZoomHeight}
          type="button"
        >
          <IconArrowAutofitHeight />
        </button>
        <button
          className="Hide ControlButton"
          title={l.HIDE}
          onClick={buttonHidePage}
          type="button"
        >
          <IconEye />
          <IconEyeOff />
        </button>
        <button
          className="Reload ControlButton"
          title={l.RELOAD}
          onClick={buttonReloadPage}
          type="button"
        >
          <IconRefresh />
        </button>
        <span className="PageIndex">{index}</span>
      </div>
      <div className="PageContent">
        <img
          id={`PageImg${index}`}
          alt=""
          className="PageImg"
          src={src}
        />
      </div>
    </div>
  );
}

export default MangaPage;

// src/svelte/MangaPage.svelte
<script lang="ts">
  import { locale } from '../core/settings';
  import { buttonBookmark } from '../ui/events/bookmarks.ts';
  import { buttonHidePage, buttonReloadPage } from '../ui/events/individual.ts';
  import {
    buttonRestoreZoom,
    buttonZoomHeight,
    buttonZoomIn,
    buttonZoomOut,
    buttonZoomWidth,
  } from '../ui/events/size.ts';
  import {
    IconArrowAutofitHeight,
    IconArrowAutofitWidth,
    IconBookmark,
    IconBookmarkOff,
    IconEye,
    IconEyeOff,
    IconRefresh,
    IconZoomCancel,
    IconZoomIn,
    IconZoomOut,
  } from '../ui/icons';

  interface Props {
    index: number;
    src?: string;
  }

  const { index, src = '' }: Props = $props();
</script>

<div class="MangaPage" id="Page{index}">
  <div class="PageFunctions">
    <button class="Bookmark ControlButton" onclick={buttonBookmark} title={$locale.BOOKMARK}>
      {@html IconBookmark}
      {@html IconBookmarkOff}
    </button>
    <button class="ZoomIn ControlButton" onclick={buttonZoomIn} title={$locale.ZOOM_IN}>
      {@html IconZoomIn}
    </button>
    <button
      class="ZoomRestore ControlButton"
      onclick={buttonRestoreZoom}
      title={$locale.ZOOM_RESET}
    >
      {@html IconZoomCancel}
    </button>
    <button class="ZoomOut ControlButton" onclick={buttonZoomOut} title={$locale.ZOOM_OUT}>
      {@html IconZoomOut}
    </button>
    <button class="ZoomWidth ControlButton" onclick={buttonZoomWidth} title={$locale.ZOOM_WIDTH}>
      {@html IconArrowAutofitWidth}
    </button>
    <button class="ZoomHeight ControlButton" onclick={buttonZoomHeight} title={$locale.ZOOM_HEIGHT}>
      {@html IconArrowAutofitHeight}
    </button>
    <button class="Hide ControlButton" onclick={buttonHidePage} title={$locale.HIDE}>
      {@html IconEye}
      {@html IconEyeOff}
    </button>
    <button class="Reload ControlButton" onclick={buttonReloadPage} title={$locale.RELOAD}>
      {@html IconRefresh}
    </button>
    <span class="PageIndex">{index}</span>
  </div>
  <div class="PageContent">
    <img alt="" class="PageImg" id="PageImg{index}" {src} />
  </div>
</div>

<style>
</style>
