// src/react/SettingsPanel-Theme.tsx
import { useStore } from '@nanostores/react';
import { locale, settings } from '../core/settings.ts';
import {
  buttonSelectTheme,
  changeColorScheme,
  changeCustomTheme,
  changeThemeShade,
} from '../ui/events/theming.ts';
import colors from '../utils/colors.ts';
import { IconCheck, IconMoon, IconPalette, IconSun } from './Icons.ts';

function SettingsPanelTheme() {
  const l = useStore(locale);
  const s = useStore(settings);

  return (
    <>
      <div className="ControlLabel ColorSchemeSelector">
        <label>{l.COLOR_SCHEME}</label>
        <button
          id="ColorScheme"
          className="ControlButton"
          onClick={changeColorScheme}
          type="button"
        >
          <IconSun />
          <IconMoon />
        </button>
      </div>
      <div className="ControlLabel ThemeSelector">
        <label>{l.THEME_COLOR}</label>
        <span
          className={`custom ThemeRadio ${s.theme === 'custom' ? 'selected' : ''}`}
          title="custom"
          onClick={buttonSelectTheme}
        >
          <IconPalette />
          <IconCheck />
        </span>
        {Object.keys(colors).map((color) => (
          <span
            key={colors[color].name}
            title={colors[color].name}
            className={`${colors[color].name} ThemeRadio ${
              s.theme === colors[color].name ? 'selected' : ''
            }`}
            onClick={buttonSelectTheme}
          >
            <IconCheck />
          </span>
        ))}
      </div>
      <div
        id="Hue"
        className={`ControlLabel CustomTheme ControlLabelItem ${
          s.theme.startsWith('custom') ? 'show' : ''
        }`}
      >
        <label>{l.THEME_HUE}</label>
        <input
          id="CustomThemeHue"
          type="color"
          value={s.customTheme}
          onChange={changeCustomTheme}
          className="colorpicker CustomTheme"
        />
      </div>
      <div
        id="Shade"
        className={`ControlLabel CustomTheme ControlLabelItem ${
          s.theme.startsWith('custom') ? '' : 'show'
        }`}
      >
        <span>
          <label>{l.THEME_SHADE}</label>
          <output id="themeShadeVal" className="RangeValue" htmlFor="ThemeShade">
            {s.themeShade}
          </output>
        </span>
        <input
          type="range"
          value={s.themeShade}
          onInput={changeThemeShade}
          name="ThemeShade"
          id="ThemeShade"
          min="100"
          max="900"
          step="100"
        />
      </div>
    </>
  );
}

export default SettingsPanelTheme;

// src/svelte/SettingsPanel-Theme.svelte
<script lang="ts">
  import { locale, settings } from '../core/settings';
  import {
    buttonSelectTheme,
    changeColorScheme,
    changeCustomTheme,
    changeThemeShade,
  } from '../ui/events/theming.ts';
  import colors from '../utils/colors.ts';
  import { IconCheck, IconMoon, IconPalette, IconSun } from '../ui/icons';
</script>

<div class="ControlLabel ColorSchemeSelector">
  <label>{$locale.COLOR_SCHEME}</label>
  <button class="ControlButton" id="ColorScheme" onclick={changeColorScheme}>
    {@html IconSun}
    {@html IconMoon}
  </button>
</div>
<div class="ControlLabel ThemeSelector">
  <label>{$locale.THEME_COLOR}</label>
  <span
    class="custom ThemeRadio
        {$settings.theme === 'custom' ? 'selected' : ''}"
    onclick={buttonSelectTheme}
    title="custom"
  >
    {@html IconPalette}
    {@html IconCheck}
  </span>
  {#each Object.keys(colors).map(color => colors[color].name) as theme}
    <span
      title={theme}
      class="{theme} ThemeRadio {$settings.theme === theme ? 'selected' : ''}"
      onclick={buttonSelectTheme}
    >
      {@html IconCheck}
    </span>
  {/each}
</div>
<div
  class="ControlLabel CustomTheme ControlLabelItem
      {$settings.theme.startsWith('custom') ? 'show' : ''}"
  id="Hue"
>
  <label>{$locale.THEME_HUE}</label>
  <input
    class="colorpicker CustomTheme"
    id="CustomThemeHue"
    onchange={changeCustomTheme}
    type="color"
    value={$settings.customTheme}
  />
</div>
<div
  class="ControlLabel CustomTheme ControlLabelItem
      {$settings.theme.startsWith('custom') ? '' : 'show'}"
  id="Shade"
>
  <span>
    <label>{$locale.THEME_SHADE}</label>
    <output class="RangeValue" for="ThemeShade" id="themeShadeVal">
      {$settings.themeShade}
    </output>
  </span>
  <input
    id="ThemeShade"
    max="900"
    min="100"
    name="ThemeShade"
    oninput={changeThemeShade}
    step="100"
    type="range"
    value={$settings.themeShade}
  />
</div>
