// src/react/SettingsPanel.tsx
import { useStore } from '@nanostores/react';
import { locale } from '../core/settings.ts';
import { buttonSettingsClose } from '../ui/events/panels.ts';
import { IconSettingsOff, IconX } from './Icons.ts';
import SettingsPanelGeneral from './SettingsPanel-General.tsx';
import SettingsPanelLoading from './SettingsPanel-Loading.tsx';
import SettingsPanelOthers from './SettingsPanel-Others.tsx';
import SettingsPanelTheme from './SettingsPanel-Theme.tsx';
import SettingsPanelZoom from './SettingsPanel-Zoom.tsx';

function SettingsPanel() {
  const l = useStore(locale);

  return (
    <div
      id="SettingsPanel"
      className="panel"
    >
      <h2>{l.SETTINGS}</h2>
      <button
        id="CloseSettings"
        className="closeButton"
        title={l.CLOSE}
        onClick={buttonSettingsClose}
        type="button"
      >
        <IconX />
      </button>
      <button
        id="ResetSettings"
        className="ControlButton"
        type="button"
      >
        <IconSettingsOff />
        {l.BUTTON_RESET_SETTINGS}
      </button>
      <fieldset>
        <legend>{l.GENERAL}</legend>
        <SettingsPanelGeneral />
      </fieldset>
      <fieldset>
        <legend>{l.THEME}</legend>
        <SettingsPanelTheme />
      </fieldset>
      <fieldset>
        <legend>{l.LOADING}</legend>
        <SettingsPanelLoading />
      </fieldset>
      <fieldset>
        <legend>{l.ZOOM}</legend>
        <SettingsPanelZoom />
      </fieldset>
      <fieldset>
        <legend>{l.OTHERS}</legend>
        <SettingsPanelOthers />
      </fieldset>
    </div>
  );
}

export default SettingsPanel;

// src/svelte/SettingsPanel.svelte
<script lang="ts">
  import { locale } from '../core/settings';
  import { buttonSettingsClose } from '../ui/events/panels.ts';
  import { IconSettingsOff, IconX } from '../ui/icons';
  import SettingsPanelGeneral from './SettingsPanel-General.svelte';
  import SettingsPanelLoading from './SettingsPanel-Loading.svelte';
  import SettingsPanelOthers from './SettingsPanel-Others.svelte';
  import SettingsPanelTheme from './SettingsPanel-Theme.svelte';
  import SettingsPanelZoom from './SettingsPanel-Zoom.svelte';
</script>

<div class="panel" id="SettingsPanel">
  <h2>{$locale.SETTINGS}</h2>
  <button
    class="closeButton"
    id="CloseSettings"
    onclick={buttonSettingsClose}
    title={$locale.CLOSE}
  >
    {@html IconX}
  </button>
  <button class="ControlButton" id="ResetSettings">
    {@html IconSettingsOff}
    {$locale.BUTTON_RESET_SETTINGS}
  </button>
  <fieldset>
    <legend>{$locale.GENERAL}</legend>
    <SettingsPanelGeneral />
  </fieldset>
  <fieldset>
    <legend>{$locale.THEME}</legend>
    <SettingsPanelTheme />
  </fieldset>
  <fieldset>
    <legend>{$locale.LOADING}</legend>
    <SettingsPanelLoading />
  </fieldset>
  <fieldset>
    <legend>{$locale.ZOOM}</legend>
    <SettingsPanelZoom />
  </fieldset>
  <fieldset>
    <legend>{$locale.OTHERS}</legend>
    <SettingsPanelOthers />
  </fieldset>
</div>

<style>
</style>
