// src/svelte/Reader.svelte
<script lang="ts">
  import { settings } from '../core/settings';
  import type { IManga } from '../types';
  import MangaPage from './MangaPage.svelte';

  interface Props {
    manga: IManga;
  }

  const { manga }: Props = $props();
</script>

<main
  class="{$settings.fitWidthIfOversize ? 'fitWidthIfOversize' : ''}
      {$settings.viewMode}"
  id="Chapter"
>
  {#each Array.from(Array(manga.pages + 1).keys()).slice(manga.begin) as index}
    <MangaPage {index} />
  {/each}
</main>

<style>
</style>

// src/react/components/Reader.tsx
import { useStore } from '@nanostores/react';
import { settings } from '../../core/settings';
import type { IManga } from '../../types';
import MangaPage from './MangaPage';

type Props = {
  manga: IManga;
};

function Reader({ manga }: Props) {
  const s = useStore(settings);
  return (
    <main
      id="Chapter"
      className={`${s.fitWidthIfOversize ? 'fitWidthIfOversize' : ''} ${s.viewMode}`}
    >
      {Array.from(Array(manga.pages + 1).keys())
        .slice(manga.begin)
        .map((index) => (
          <MangaPage index={index} key={index} />
        ))}
    </main>
  );
}

export default Reader;
