// src/svelte/SettingsPanel-Others.svelte
<script lang="ts">
  import { locale, settings } from '../core/settings';
  import {
    changeHeaderType,
    changeLazyStart,
    changeScrollHeight,
    checkAutoDownload,
    checkEnableComments,
    checkFitWidthOversize,
    checkHideImageControls,
    checkLazyLoad,
    checkShowThumbnails,
    checkVerticalSeparator,
  } from '../ui/events/options.ts';
  import Toggler from './Toggler.svelte';
</script>

<div class="ControlLabel verticalSeparator">
  {$locale.VERTICAL_SEPARATOR}
  <Toggler
    checked={$settings.verticalSeparator}
    name="verticalSeparator"
    onchange={checkVerticalSeparator}
  ></Toggler>
</div>

<div class="ControlLabel fitIfOversize">
  {$locale.FIT_WIDTH_OVERSIZED}
  <Toggler
    checked={$settings.fitWidthIfOversize}
    name="fitIfOversize"
    onchange={checkFitWidthOversize}
  ></Toggler>
</div>

<div class="ControlLabel showThumbnails">
  {$locale.SHOW_THUMBNAILS}
  <Toggler checked={$settings.showThumbnails} name="showThumbnails" onchange={checkShowThumbnails}
  ></Toggler>
</div>

<div class="ControlLabel enableComments">
  {$locale.ENABLE_COMMENTS}
  <Toggler checked={$settings.enableComments} name="enableComments" onchange={checkEnableComments}
  ></Toggler>
</div>

<div class="ControlLabel downloadZip">
  {$locale.DOWNLOAD_IMAGES}
  <Toggler checked={$settings.downloadZip} name="downloadZip" onchange={checkAutoDownload}
  ></Toggler>
</div>

<div class="ControlLabel hidePageControls">
  {$locale.HIDE_CONTROLS}
  <Toggler
    checked={$settings.hidePageControls}
    name="hidePageControls"
    onchange={checkHideImageControls}
  ></Toggler>
</div>

<div class="ControlLabel lazyLoadImages">
  {$locale.LAZY_LOAD_IMAGES_ENABLE}
  <Toggler checked={$settings.lazyLoadImages} name="lazyLoadImages" onchange={checkLazyLoad}
  ></Toggler>
</div>

<div
  class="ControlLabel lazyStart ControlLabelItem
    {$settings.lazyLoadImages ? 'show' : ''}"
>
  <span>
    {$locale.LAZY_LOAD_IMAGES}
    <output for="lazyStart" id="lazyStartVal"> {$settings.lazyStart} </output>
  </span>
  <input
    id="lazyStart"
    max="100"
    min="5"
    name="lazyStart"
    oninput={changeLazyStart}
    step="5"
    type="range"
    value={$settings.lazyStart}
  />
</div>

<div class="ControlLabel autoScroll">
  <span>
    {$locale.AUTO_SCROLL_HEIGHT}
    <output for="scrollHeight" id="scrollHeightVal">
      {$settings.scrollHeight}
    </output>px
  </span>
  <input
    id="scrollHeight"
    max="100"
    min="1"
    name="scrollHeight"
    oninput={changeScrollHeight}
    step="1"
    type="range"
    value={$settings.scrollHeight}
  />
</div>

<div class="ControlLabel headerType">
  {$locale.HEADER_TYPE}
  <select id="headerType" onchange={changeHeaderType} value={$settings.header}>
    <option value="hover">
      {$locale.HEADER_HOVER}
    </option>
    <option value="scroll">
      {$locale.HEADER_SCROLL}
    </option>
    <option value="click">
      {$locale.HEADER_CLICK}
    </option>
    <option value="fixed">
      {$locale.HEADER_FIXED}
    </option>
    <option value="simple">
      {$locale.HEADER_SIMPLE}
    </option>
  </select>
</div>

// src/react/components/SettingsPanel-Others.tsx
import { useStore } from '@nanostores/react';
import { locale, settings } from '../../core/settings';
import {
  changeHeaderType,
  changeLazyStart,
  changeScrollHeight,
  checkAutoDownload,
  checkEnableComments,
  checkFitWidthOversize,
  checkHideImageControls,
  checkLazyLoad,
  checkShowThumbnails,
  checkVerticalSeparator,
} from '../../ui/events/options';
import Toggler from './Toggler';

function SettingsPanelOthers() {
  const l = useStore(locale);
  const s = useStore(settings);

  return (
    <>
      <div className="ControlLabel verticalSeparator">
        {l.VERTICAL_SEPARATOR}
        <Toggler
          name="verticalSeparator"
          checked={s.verticalSeparator}
          onChange={checkVerticalSeparator}
        />
      </div>

      <div className="ControlLabel fitIfOversize">
        {l.FIT_WIDTH_OVERSIZED}
        <Toggler
          name="fitIfOversize"
          checked={s.fitWidthIfOversize}
          onChange={checkFitWidthOversize}
        />
      </div>

      <div className="ControlLabel showThumbnails">
        {l.SHOW_THUMBNAILS}
        <Toggler name="showThumbnails" checked={s.showThumbnails} onChange={checkShowThumbnails} />
      </div>

      <div className="ControlLabel enableComments">
        {l.ENABLE_COMMENTS}
        <Toggler name="enableComments" checked={s.enableComments} onChange={checkEnableComments} />
      </div>

      <div className="ControlLabel downloadZip">
        {l.DOWNLOAD_IMAGES}
        <Toggler name="downloadZip" checked={s.downloadZip} onChange={checkAutoDownload} />
      </div>

      <div className="ControlLabel hidePageControls">
        {l.HIDE_CONTROLS}
        <Toggler
          name="hidePageControls"
          checked={s.hidePageControls}
          onChange={checkHideImageControls}
        />
      </div>

      <div className="ControlLabel lazyLoadImages">
        {l.LAZY_LOAD_IMAGES_ENABLE}
        <Toggler name="lazyLoadImages" checked={s.lazyLoadImages} onChange={checkLazyLoad} />
      </div>

      <div className={`ControlLabel lazyStart ControlLabelItem ${s.lazyLoadImages ? 'show' : ''}`}>
        <span>
          {l.LAZY_LOAD_IMAGES}
          <output id="lazyStartVal" htmlFor="lazyStart">
            {s.lazyStart}
          </output>
        </span>
        <input
          type="range"
          value={s.lazyStart}
          onInput={changeLazyStart}
          name="lazyStart"
          id="lazyStart"
          min="5"
          max="100"
          step="5"
        />
      </div>

      <div className="ControlLabel autoScroll">
        <span>
          {l.AUTO_SCROLL_HEIGHT}
          <output id="scrollHeightVal" htmlFor="scrollHeight">
            {s.scrollHeight}
          </output>
          px
        </span>
        <input
          type="range"
          value={s.scrollHeight}
          onInput={changeScrollHeight}
          name="scrollHeight"
          id="scrollHeight"
          min="1"
          max="100"
          step="1"
        />
      </div>

      <div className="ControlLabel headerType">
        {l.HEADER_TYPE}
        <select id="headerType" value={s.header} onChange={changeHeaderType}>
          <option value="hover">{l.HEADER_HOVER}</option>
          <option value="scroll">{l.HEADER_SCROLL}</option>
          <option value="click">{l.HEADER_CLICK}</option>
          <option value="fixed">{l.HEADER_FIXED}</option>
          <option value="simple">{l.HEADER_SIMPLE}</option>
        </select>
      </div>
    </>
  );
}

export default SettingsPanelOthers;
