// src/svelte/Thumbnail.svelte
<script lang="ts">
  import { clickThumbnail } from '../ui/events/navigation.ts';

  interface Props {
    index: number;
    src?: string;
  }

  const { index, src = '' }: Props = $props();
</script>

<div
  class="Thumbnail"
  id="Thumbnail{index}"
  onclick={clickThumbnail}
>
  <img
    alt=""
    class="ThumbnailImg"
    id="ThumbnailImg{index}"
    {src}
  />
  <span class="ThumbnailIndex">{index}</span>
</div>

// src/react/components/Thumbnail.tsx
import { clickThumbnail } from '../../ui/events/navigation';

type Props = {
  index: number;
  src?: string;
};

function Thumbnail({ index, src = '' }: Props) {
  return (
    <div id={`Thumbnail${index}`} className="Thumbnail" onClick={clickThumbnail}>
      <img id={`ThumbnailImg${index}`} alt="" className="ThumbnailImg" src={src} />
      <span className="ThumbnailIndex">{index}</span>
    </div>
  );
}

export default Thumbnail;
