// src/svelte/Header.svelte
<script lang="ts">
  import { locale, settings } from '../core/settings';
  import type { IManga } from '../types';
  import { toggleAutoScroll } from '../ui/events/autoscroll.ts';
  import { buttonBookmarksOpen } from '../ui/events/bookmarks.ts';
  import {
    buttonCommentsOpen,
    buttonGlobalHideImageControls,
    buttonRedirectURL,
    buttonStartDownload,
  } from '../ui/events/globals.ts';
  import { selectGoToPage } from '../ui/events/navigation.ts';
  import { buttonKeybindingsOpen, buttonSettingsOpen } from '../ui/events/panels.ts';
  import { updateViewMode } from '../ui/events/viewmode.ts';
  import { changeGlobalZoom, changeZoom, changeZoomByStep } from '../ui/events/zoom.ts';
  import {
    IconArrowAutofitDown,
    IconArrowAutofitHeight,
    IconArrowAutofitLeft,
    IconArrowAutofitRight,
    IconArrowAutofitWidth,
    IconArrowBigLeft,
    IconArrowBigRight,
    IconBookmarks,
    IconFileDownload,
    IconKeyboard,
    IconListNumbers,
    IconLoader2,
    IconMenu2,
    IconMessage,
    IconPlayerPause,
    IconPlayerPlay,
    IconSettings,
    IconSpacingVertical,
    IconZoomInArea,
    IconZoomOutArea,
    IconZoomPan,
  } from '../ui/icons';

  interface Props {
    manga: IManga;
  }

  const { manga }: Props = $props();
</script>

<div id="menu">
  {@html IconMenu2}
</div>
<header class="{$settings.header} headroom-top" id="Header">
  <aside id="GlobalFunctions">
    <span>
      <button
        class="ControlButton"
        id="enlarge"
        onclick={changeZoomByStep(1)}
        title={$locale.ENLARGE}
      >
        {@html IconZoomInArea}
      </button>
      <button
        class="ControlButton"
        id="restore"
        onclick={changeGlobalZoom('percent')}
        title={$locale.RESTORE}
      >
        {@html IconZoomPan}
      </button>
      <button
        class="ControlButton"
        id="reduce"
        onclick={changeZoomByStep(-1)}
        title={$locale.REDUCE}
      >
        {@html IconZoomOutArea}
      </button>
      <button
        class="ControlButton"
        id="fitWidth"
        onclick={changeGlobalZoom('width')}
        title={$locale.FIT_WIDTH}
      >
        {@html IconArrowAutofitWidth}
      </button>
      <button
        class="ControlButton"
        id="fitHeight"
        onclick={changeGlobalZoom('height')}
        title={$locale.FIT_HEIGHT}
      >
        {@html IconArrowAutofitHeight}
      </button>
      <button
        class="ControlButton"
        id="keybindings"
        onclick={buttonKeybindingsOpen}
        title={$locale.KEYBINDINGS}
      >
        {@html IconKeyboard}
      </button>
      <button
        class="ControlButton phones"
        id="AutoScroll"
        onclick={toggleAutoScroll}
        title={$locale.SCROLL_START}
      >
        {@html IconPlayerPlay}
        {@html IconPlayerPause}
      </button>
    </span>
    <span>
      <button
        class="ControlButton"
        id="ltrMode"
        onclick={updateViewMode('FluidLTR')}
        title={$locale.VIEW_MODE_LEFT}
      >
        {@html IconArrowAutofitRight}
      </button>
      <button
        class="ControlButton tablets"
        id="verticalMode"
        onclick={updateViewMode('Vertical')}
        title={$locale.VIEW_MODE_VERTICAL}
      >
        {@html IconArrowAutofitDown}
      </button>
      <button
        class="ControlButton tablets"
        id="webComic"
        onclick={updateViewMode('WebComic')}
        title={$locale.VIEW_MODE_WEBCOMIC}
      >
        {@html IconSpacingVertical}
      </button>
      <button
        class="ControlButton"
        id="rtlMode"
        onclick={updateViewMode('FluidRTL')}
        title={$locale.VIEW_MODE_RIGHT}
      >
        {@html IconArrowAutofitLeft}
      </button>
      <button
        class="ControlButton tablets"
        id="pageControls"
        onclick={buttonGlobalHideImageControls}
        title={$locale.TOGGLE_CONTROLS}
      >
        {@html IconListNumbers}
      </button>
      <button
        class="ControlButton tablets"
        id="bookmarks"
        onclick={buttonBookmarksOpen}
        title={$locale.BOOKMARKS}
      >
        {@html IconBookmarks}
      </button>
      <button
        class="ControlButton tablets phones"
        id="settings"
        onclick={buttonSettingsOpen}
        title={$locale.SETTINGS}
      >
        {@html IconSettings}
      </button>
    </span>
    <span id="ZoomSlider">
      <output class="RangeValue" for="Zoom" id="ZoomVal">
        {$settings.zoomMode === 'percent' ? $settings.defaultZoom + '%' : $settings.zoomMode}
      </output>
      <input
        id="Zoom"
        max="200"
        min="1"
        name="Zoom"
        oninput={changeZoom}
        type="range"
        value={$settings.defaultZoom}
      />
    </span>
  </aside>
  <div class="ViewerTitle">
    <h1 id="MangaTitle">{manga.title}</h1>
    <a href={manga.series} id="series" onclick={buttonRedirectURL}>
      ({$locale.RETURN_CHAPTER_LIST})
    </a>
  </div>
  <nav id="ChapterNavigation">
    <div class="ControlLabel" id="Counters">
      {$locale.PAGES_LOADED}:
      <i>0</i> /
      <b>{manga.begin && manga.begin > 1 ? manga.pages - (manga.begin - 1) : manga.pages}</b>
      <span class="ControlLabel">
        {$locale.GO_TO_PAGE}:
      </span>
      <select id="gotoPage" onchange={selectGoToPage}>
        <option selected>#</option>
        {#each Array.from(Array(manga.pages + 1).keys()).slice(manga.begin) as index}
          <option value={index}>{index}</option>
        {/each}
      </select>
    </div>
    <div class="ChapterControl" id="ChapterControl">
      <button
        class="NavigationControlButton ControlButton {manga.comments ? '' : 'disabled'}"
        id="CommentsButton"
        onclick={buttonCommentsOpen}
        title={$locale.DISPLAY_COMMENTS}
      >
        {@html IconMessage}
        {$locale.DISPLAY_COMMENTS}
      </button>
      <button
        class="NavigationControlButton ControlButton disabled"
        id="download"
        onclick={buttonStartDownload}
        title={$locale.DOWNLOAD_ZIP}
        type="button"
      >
        {@html IconFileDownload}
        {@html IconLoader2}
        {$locale.BUTTON_DOWNLOAD}
      </button>
      <a
        class="NavigationControlButton ControlButton"
        href={manga.prev ?? ''}
        id="prev"
        onclick={buttonRedirectURL}
        title={$locale.PREVIOUS_CHAPTER}
        type="button"
      >
        {@html IconArrowBigLeft}
        {$locale.BUTTON_PREVIOUS}
      </a>
      <a
        class="NavigationControlButton ControlButton"
        href={manga.next ?? ''}
        id="next"
        onclick={buttonRedirectURL}
        title={$locale.NEXT_CHAPTER}
        type="button"
      >
        {$locale.BUTTON_NEXT}
        {@html IconArrowBigRight}
      </a>
    </div>
  </nav>
</header>

<style>
</style>

// src/react/Header.tsx
import { useStore } from '@nanostores/react';
import { locale, settings } from '../core/settings.ts';
import type { IManga } from '../types';
import { toggleAutoScroll } from '../ui/events/autoscroll.ts';
import { buttonBookmarksOpen } from '../ui/events/bookmarks.ts';
import {
  buttonCommentsOpen,
  buttonGlobalHideImageControls,
  buttonRedirectURL,
  buttonStartDownload,
} from '../ui/events/globals.ts';
import { selectGoToPage } from '../ui/events/navigation.ts';
import { buttonKeybindingsOpen, buttonSettingsOpen } from '../ui/events/panels.ts';
import { updateViewMode } from '../ui/events/viewmode.ts';
import { changeGlobalZoom, changeZoom, changeZoomByStep } from '../ui/events/zoom.ts';
import {
  IconArrowAutofitDown,
  IconArrowAutofitHeight,
  IconArrowAutofitLeft,
  IconArrowAutofitRight,
  IconArrowAutofitWidth,
  IconArrowBigLeft,
  IconArrowBigRight,
  IconBookmarks,
  IconFileDownload,
  IconKeyboard,
  IconListNumbers,
  IconLoader2,
  IconMenu2,
  IconMessage,
  IconPlayerPause,
  IconPlayerPlay,
  IconSettings,
  IconSpacingVertical,
  IconZoomInArea,
  IconZoomOutArea,
  IconZoomPan,
} from './Icons.ts';

type Props = {
  manga: IManga;
};

function Header({ manga }: Props) {
  const l = useStore(locale);
  const s = useStore(settings);

  return (
    <>
      <div id="menu">
        <IconMenu2 />
      </div>
      <header id="Header" className={`${s.header} headroom-top`}>
        <aside id="GlobalFunctions">
          <span>
            <button
              id="enlarge"
              title={l.ENLARGE}
              className="ControlButton"
              onClick={changeZoomByStep(1)}
              type="button"
            >
              <IconZoomInArea />
            </button>
            <button
              id="restore"
              title={l.RESTORE}
              className="ControlButton"
              onClick={() => changeGlobalZoom('percent')}
              type="button"
            >
              <IconZoomPan />
            </button>
            <button
              id="reduce"
              title={l.REDUCE}
              className="ControlButton"
              onClick={changeZoomByStep(-1)}
              type="button"
            >
              <IconZoomOutArea />
            </button>
            <button
              id="fitWidth"
              title={l.FIT_WIDTH}
              className="ControlButton"
              onClick={() => changeGlobalZoom('width')}
              type="button"
            >
              <IconArrowAutofitWidth />
            </button>
            <button
              id="fitHeight"
              title={l.FIT_HEIGHT}
              className="ControlButton"
              onClick={() => changeGlobalZoom('height')}
              type="button"
            >
              <IconArrowAutofitHeight />
            </button>
            <button
              id="keybindings"
              title={l.KEYBINDINGS}
              className="ControlButton"
              onClick={buttonKeybindingsOpen}
              type="button"
            >
              <IconKeyboard />
            </button>
            <button
              id="AutoScroll"
              title={l.SCROLL_START}
              className="ControlButton phones"
              onClick={toggleAutoScroll}
              type="button"
            >
              <IconPlayerPlay />
              <IconPlayerPause />
            </button>
          </span>
          <span>
            <button
              id="ltrMode"
              title={l.VIEW_MODE_LEFT}
              className="ControlButton"
              onClick={() => updateViewMode('FluidLTR')}
              type="button"
            >
              <IconArrowAutofitRight />
            </button>
            <button
              id="verticalMode"
              title={l.VIEW_MODE_VERTICAL}
              className="ControlButton tablets"
              onClick={() => updateViewMode('Vertical')}
              type="button"
            >
              <IconArrowAutofitDown />
            </button>
            <button
              id="webComic"
              title={l.VIEW_MODE_WEBCOMIC}
              className="ControlButton tablets"
              onClick={() => updateViewMode('WebComic')}
              type="button"
            >
              <IconSpacingVertical />
            </button>
            <button
              id="rtlMode"
              title={l.VIEW_MODE_RIGHT}
              className="ControlButton"
              onClick={() => updateViewMode('FluidRTL')}
              type="button"
            >
              <IconArrowAutofitLeft />
            </button>
            <button
              id="pageControls"
              title={l.TOGGLE_CONTROLS}
              className="ControlButton tablets"
              onClick={buttonGlobalHideImageControls}
              type="button"
            >
              <IconListNumbers />
            </button>
            <button
              id="bookmarks"
              title={l.BOOKMARKS}
              className="ControlButton tablets"
              onClick={buttonBookmarksOpen}
              type="button"
            >
              <IconBookmarks />
            </button>
            <button
              id="settings"
              title={l.SETTINGS}
              className="ControlButton tablets phones"
              onClick={buttonSettingsOpen}
              type="button"
            >
              <IconSettings />
            </button>
          </span>
          <span id="ZoomSlider">
            <output id="ZoomVal" className="RangeValue" htmlFor="Zoom">
              {s.zoomMode === 'percent' ? `${s.defaultZoom}%` : s.zoomMode}
            </output>
            <input
              type="range"
              value={s.defaultZoom}
              name="Zoom"
              id="Zoom"
              min="1"
              max="200"
              onInput={changeZoom}
            />
          </span>
        </aside>
        <div className="ViewerTitle">
          <h1 id="MangaTitle">{manga.title}</h1>
          <a id="series" href={manga.series ?? ''} onClick={buttonRedirectURL}>
            ({l.RETURN_CHAPTER_LIST})
          </a>
        </div>
        <nav id="ChapterNavigation">
          <div id="Counters" className="ControlLabel">
            {l.PAGES_LOADED}:<i>0</i> /
            <b>{manga.begin && manga.begin > 1 ? manga.pages - (manga.begin - 1) : manga.pages}</b>
            <span className="ControlLabel">{l.GO_TO_PAGE}:</span>
            <select id="gotoPage" onChange={selectGoToPage}>
              <option selected>#</option>
              {Array.from(Array(manga.pages + 1).keys())
                .slice(manga.begin)
                .map((index) => (
                  <option value={index} key={index}>
                    {index}
                  </option>
                ))}
            </select>
          </div>
          <div id="ChapterControl" className="ChapterControl">
            <button
              id="CommentsButton"
              className={`NavigationControlButton ControlButton ${manga.comments ? '' : 'disabled'}`}
              title={l.DISPLAY_COMMENTS}
              onClick={buttonCommentsOpen}
              type="button"
            >
              <IconMessage />
              {l.DISPLAY_COMMENTS}
            </button>
            <button
              id="download"
              className="NavigationControlButton ControlButton disabled"
              type="button"
              title={l.DOWNLOAD_ZIP}
              onClick={buttonStartDownload}
            >
              <IconFileDownload />
              <IconLoader2 />
              {l.BUTTON_DOWNLOAD}
            </button>
            <a
              id="prev"
              className="NavigationControlButton ControlButton"
              type="button"
              href={manga.prev ?? ''}
              title={l.PREVIOUS_CHAPTER}
              onClick={buttonRedirectURL}
            >
              <IconArrowBigLeft />
              {l.BUTTON_PREVIOUS}
            </a>
            <a
              id="next"
              className="NavigationControlButton ControlButton"
              type="button"
              href={manga.next ?? ''}
              title={l.NEXT_CHAPTER}
              onClick={buttonRedirectURL}
            >
              {l.BUTTON_NEXT}
              <IconArrowBigRight />
            </a>
          </div>
        </nav>
      </header>
    </>
  );
}

export default Header;
