// src/svelte/SettingsPanel-General.svelte
<script lang="ts">
  import { isSettingsLocal, locale, settings } from '../core/settings';
  import locales from '../locales';
  import { changeLocale, changeSettingsScope } from '../ui/events/options.ts';
  import { IconLocationCog, IconWorldCog } from '../ui/icons';
</script>

<div class="ControlLabel">
  {$locale.SCOPE}
  <div class="radio-inputs" id="SettingsScope">
    <label class="radio">
      <input
        checked={!isSettingsLocal()}
        id="globalSettings"
        name="settingsScope"
        onchange={changeSettingsScope}
        type="radio"
        value="false"
      />
      <span class="name">{@html IconWorldCog} {$locale.GLOBAL}</span>
    </label>
    <label class="radio">
      <input
        checked={isSettingsLocal()}
        id="localSettings"
        name="settingsScope"
        onchange={changeSettingsScope}
        type="radio"
        value="true"
      />
      <span class="name">{@html IconLocationCog} {window.location.hostname}</span>
    </label>
  </div>
</div>
<div class="ControlLabel locale">
  {$locale.LANGUAGE}
  <select id="locale" onchange={changeLocale} value={$settings.locale}>
    {#each locales as locale}
      <option value="${locale.ID}">
        {locale.NAME}
      </option>
    {/each}
  </select>
</div>

// src/react/SettingsPanel-General.tsx
import { useStore } from '@nanostores/react';
import { isSettingsLocal, locale, settings } from '../core/settings.ts';
import locales from '../locales';
import { changeLocale, changeSettingsScope } from '../ui/events/options.ts';
import { IconLocationCog, IconWorldCog } from './Icons.ts';

function SettingsPanelGeneral() {
  const l = useStore(locale);
  const s = useStore(settings);

  return (
    <>
      <div className="ControlLabel">
        {l.SCOPE}
        <div id="SettingsScope" className="radio-inputs">
          <label className="radio">
            <input
              type="radio"
              id="globalSettings"
              name="settingsScope"
              value="false"
              checked={!isSettingsLocal()}
              onChange={changeSettingsScope}
            />
            <span className="name">
              <IconWorldCog /> {l.GLOBAL}
            </span>
          </label>
          <label className="radio">
            <input
              type="radio"
              id="localSettings"
              name="settingsScope"
              value="true"
              checked={isSettingsLocal()}
              onChange={changeSettingsScope}
            />
            <span className="name">
              <IconLocationCog /> {window.location.hostname}
            </span>
          </label>
        </div>
      </div>
      <div className="ControlLabel locale">
        {l.LANGUAGE}
        <select id="locale" value={s.locale} onChange={changeLocale}>
          {locales.map((loc) => (
            <option value={loc.ID} key={loc.ID}>
              {loc.NAME}
            </option>
          ))}
        </select>
      </div>
    </>
  );
}

export default SettingsPanelGeneral;
