// src/svelte/ThumbnailPanel.svelte
<script lang="ts">
import { locale, settings } from '../core/settings';
import type { IManga } from '../types';
import { transformScrollToHorizontal } from '../ui/events/common.ts';
import { IconCategory } from '../ui/icons';
import Thumbnail from './Thumbnail.svelte';

interface Props {
  manga: IManga;
}

const { manga }: Props = $props();
</script>

<nav
  class="panel {$settings.showThumbnails ? '' : 'disabled'}"
  id="Navigation"
>
  <div
    class="ControlLabel"
    id="NavigationCounters"
  >
    {@html IconCategory}
    <i>0</i> /
    <b>{manga.begin && manga.begin > 1 ? manga.pages - (manga.begin - 1) : manga.pages}</b>
    {$locale.PAGES_LOADED}
  </div>
  <div
    id="Thumbnails"
    onwheel={transformScrollToHorizontal}
  >
    {#each Array.from(Array(manga.pages + 1).keys()).slice(manga.begin) as index}
      <Thumbnail {index} />
    {/each}
  </div>
</nav>

<style>
</style>

// src/react/ThumbnailPanel.tsx
import { useStore } from '@nanostores/react';
import { locale, settings } from '../core/settings.ts';
import type { IManga } from '../types';
import { transformScrollToHorizontal } from '../ui/events/common.ts';
import { IconCategory } from './Icons.ts';
import Thumbnail from './Thumbnail.tsx';

type Props = {
  manga: IManga;
};

function ThumbnailPanel({ manga }: Props) {
  const l = useStore(locale);
  const s = useStore(settings);

  return (
    <nav id="Navigation" className={`panel ${s.showThumbnails ? '' : 'disabled'}`}>
      <div id="NavigationCounters" className="ControlLabel">
        <IconCategory />
        <i>0</i> /
        <b>{manga.begin && manga.begin > 1 ? manga.pages - (manga.begin - 1) : manga.pages}</b>
        {l.PAGES_LOADED}
      </div>
      <div id="Thumbnails" onWheel={transformScrollToHorizontal}>
        {Array.from(Array(manga.pages + 1).keys())
          .slice(manga.begin)
          .map((index) => (
            <Thumbnail index={index} key={index} />
          ))}
      </div>
    </nav>
  );
}

export default ThumbnailPanel;
