// src/svelte/Toggler.svelte
<script lang="ts">
  import { IconCheck, IconX } from '../ui/icons';

  interface Props {
    name: string;
    checked?: boolean;
    onchange?: (e: Event) => void;
  }

  let { name, checked = false, onchange }: Props = $props();
</script>

<div class="toggler">
  <input {checked} id={name} {name} {onchange} type="checkbox" value="true" />
  <label for={name}>
    {@html IconCheck}
    {@html IconX}
  </label>
</div>

// src/react/Toggler.tsx
import type { ChangeEventHandler } from 'react';
import { IconCheck, IconX } from './Icons.ts';

type Props = {
  name: string;
  checked?: boolean;
  onChange?: ChangeEventHandler<HTMLInputElement>;
};

function Toggler({ name, checked = false, onChange }: Props) {
  return (
    <div className="toggler">
      <input
        id={name}
        name={name}
        type="checkbox"
        value="true"
        checked={checked}
        onChange={onChange}
      />
      <label htmlFor={name}>
        <IconCheck />
        <IconX />
      </label>
    </div>
  );
}

export default Toggler;
